### PR TITLE
Allow for imports from scripts directory

### PR DESCRIPTION
**Pull request by scottx611x**
Just adding an `__init__.py` to the scripts dir.

Working with @pkerpedjiev and we're in need of importing [recursive_agg_onefile.py](https://github.com/mirnylab/cooler/blob/master/scripts/recursive_agg_onefile.py) in https://github.com/hms-dbmi/clodius

### CODE REVIEW

**Comment by nvictus** [comment]
Making top-level `scripts` importable is a bad idea. How about we move `recursive_agg_onefile.py` to a subpackage called `cooler.contrib`?

Most of what's in scripts was cruft to be deleted anyhow.

**Comment by scottx611x** [comment]
@nvictus Sounds good to me! Still new to packaging, thanks for the tip (and help)!

**Comment by nvictus** [comment]
If f510ff3 solves your issue, I'll close this. I'm not including the top-level import, so this will require explicitly importing cooler.contrib, e.g.: `from cooler.contrib import recursive_agg_onefile`.

**Comment by scottx611x** [comment]
@nvictus So this solves the issue for being able to use `recursive_agg_onefile` in a clone of `cooler` itself:

```
cooler-venv > cooler > master$ python
bpython version 0.16 on top of Python 2.7.12 /usr/local/opt/python/bin/python2.7
>>> from cooler.contrib import recursive_agg_onefile
>>>
```

But I'm trying to do a pip install of `cooler` from [clodius](https://github.com/hms-dbmi/clodius), and then import `recursive_agg_onefile` into my namespace there.

```
clodius-venv > clodius > develop$ python
bpython version 0.16 on top of Python 2.7.12 /usr/local/opt/python/bin/python2.7
>>> from cooler.contrib import recursive_agg_onefile
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    from cooler.contrib import recursive_agg_onefile
ImportError: No module named cooler.contrib
>>>
```

I've installed your changes in both cases by running a:

`pip install -e git://github.com/mirnylab/cooler@f510ff3c10087b13246024d89a1331614d5e585d#egg=cooler-master`

**Comment by scottx611x** [comment]
@nvictus Nevermind I had a cached copy in `clodius`. this is working fine now!

**Pull request closed without merging**
